### ISSUE TITLE
Issue about evaluating Recall@k

### ISSUE THREAD

**Issue by iwangjian** [seketeam/EvoCodeBench#3]
Hi, many thanks for your innovative work and for sharing the code and data! I found that when evaluating Recall@k, an error occurred for the code line `from add_func_call import process` in `recall_k.py` since `No module named 'add_func_call'`. I also checked that there's no publicly available Python package called `add_func_call`. Could the authors share how to fix that issue? Thank you very much.

**Comment by LJ2lijia** [comment]
Thank you for your suggestion. We have supplemented the `parser/add_func_all.py`.  If you have any questions, please feel free to contact us again.
